# Generated by Django 5.1.5 on 2025-03-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='vector_db_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
